services:
  web:
    container_name: dagobah-task-frontend
    image: node:20-slim
    ports:
      - 8089:8089
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
